// <auto-generated />
using ClientPortal_API.Data.v1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientPortal_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230217124817_InventoryWidgetView")]
    partial class InventoryWidgetView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientPortal_API.Schemas.v1.Widget+Asn", b =>
                {
                    b.Property<int>("ArrivedCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "arrivedCount");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("InProcessCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "inProcessCount");

                    b.Property<int>("NonconformingCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "nonconformingCount");

                    b.Property<int>("PendingCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "pendingCount");

                    b.ToTable((string)null);

                    b.ToView("vw_portal_wiget_asn", (string)null);
                });

            modelBuilder.Entity("ClientPortal_API.Schemas.v1.Widget+Inventory", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DamagedProductCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "damagedProductCount");

                    b.Property<int>("LowStockProductCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "lowInventory");

                    b.Property<int>("OutOfStockProductCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "outOfStockProductCount");

                    b.ToTable((string)null);

                    b.ToView("vw_portal_widget_average_returns", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
